@startgantt
[Dataset preparation] lasts 14 days
[Image augmentation] lasts 1 days
[Train model A] lasts 5 days
[Train model B] lasts 5 days
[Evaluate model A] lasts 5 days
[Evaluate model B] lasts 5 days
[Data analysis] lasts 14 days
[Write report] lasts 21 days
Project starts 2023-11-01
saturday are closed
sunday are closed

[Dataset preparation] starts 2023-11-01
[Image augmentation] starts at [Dataset preparation]'s end
[Image augmentation] is colored in Lavender/LightBlue
[Train model A] starts at [Image augmentation]'s end
[Evaluate model A] starts at [Train model A]'s end
[Train model B] starts at [Image augmentation]'s end
[Evaluate model B] starts at [Train model B]'s end
[Data analysis] starts at [Evaluate model A]'s end
[Data analysis] starts at [Evaluate model B]'s end
[Write report] starts at [Data analysis]'s end
@endgantt
